---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: data
  labels:
    volume: data
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  nfs:
    path: /Volumes/${VOLUME}
    server: 192.168.2.52
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: data-claim
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  selector:
    matchLabels:
      volume: data
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: skyfactory-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: skyfactory
    spec:
      containers:
      - name: java
        image: java
        args:
        - /data/Skyfactory/start.sh
        stdin: true
        ports:
        - containerPort: 25565
        volumeMounts:
        - name: data
          mountPath: /data
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: data-claim
---
kind: Service
apiVersion: v1
metadata:
  name: skyfactory-2
spec:
  type: LoadBalancer
  selector:
    app: skyfactory
  ports:
  - protocol: TCP
    port: ${PORT}
    targetPort: 25565
